# Change these first
owner: dis002 # เปลี่ยนเป็น GitHub username ของคุณ
repo: status # เปลี่ยนเป็นชื่อ repository ที่คุณสร้างสำหรับ upptime

sites:
  - name: หน้าเว็บหลัก
    url: https://t6official.shop
  - name: API เกตเวย์
    url: https://t6official.shop

status-website:
  # ถ้ามี custom domain ใส่ cname โดยเปลี่ยนเป็นโดเมนของคุณเอง หรือสามารถลบออกได้
  # cname: demo.upptime.js.org
  # กรณีไม่มี custom domain ให้ใช้ baseUrl เป็น /ชื่อ-repo
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**Status** ระบบตรวจสอบสถานะออนไลน์ด้วย Upptime"
  introMessage: นี่คือหน้าแสดงสถานะระบบแบบเรียลไทม์ผ่าน [GitHub repository](https://github.com/dis002/status) ไม่ต้องใช้ server — แค่ใช้ GitHub Actions, Issues และ Pages [**สร้างของคุณเองฟรี**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dis002/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
